AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RootDomainName:
    Default: pastyandchablis.com
    Description: Domain name for your website (pastyandchablis.com)
    Type: String

  EmailFrom:
    Description: Email address used to send email FROM with SES
    Type: String
    Default: order@pastyandchablis.com

  EmailTo:
    Description: Email address used to send email TO with SES
    Type: String

Resources:

LambdaOrderFunction:

  Type: AWS::Lambda::Function
  Properties:
    Code:
      ZipFile: |
        def handler(event, context):
          response = {
            'isBase64Encoded': False,
            'statusCode': 200,
            'headers': {},
            'multiValueHeaders': {},
            'body': 'Hello, World!'
          }
          return response
    Description: AWS Lambda function to SES email and store in DynamDB
    FunctionName: 'lambdaOrder'
    Handler: index.handler
    MemorySize: 256
    Role: !GetAtt lambdaOrder-IamRole.Arn
    Runtime: python3.7
    Timeout: 60


